/*CREATE TABLE EVENTO(
	ID_Evento INTEGER NOT NULL AUTO_INCREMENT,
    Nome_Evento VARCHAR(20) NOT NULL,
    Inicio_Evento DATETIME NOT NULL,
    Termino_Evento DATETIME NOT NULL,
    Num_Vagas_Evento INTEGER NOT NULL,
    Vlr_Ingresso_Evento DOUBLE NOT NULL,
    Qtd_Assentos INTEGER NOT NULL,
    Img_Cartaz_Evento VARCHAR(200) NOT NULL,
    PRIMARY KEY (ID_Evento)
);

CREATE TABLE ASSENTOS(
	ID_Assento INTEGER NOT NULL AUTO_INCREMENT,
    Col_Assento INTEGER NOT NULL,
    Fil_Assento INTEGER NOT NULL,
    Situacao_Assento BOOLEAN NOT NULL,
    PRIMARY KEY (ID_Assento)
);

CREATE TABLE EVENTO_ASSENTO(
	PK_Evento INTEGER,
    PK_Assento INTEGER,
    FOREIGN KEY (PK_Evento) REFERENCES EVENTO(ID_Evento),
    FOREIGN KEY (PK_Assento) REFERENCES ASSENTOS(ID_Assento)
);*/

SELECT * FROM EVENTO E
LEFT JOIN EVENTO_ASSENTO EA ON EA.PK_Evento = E.ID_Evento
LEFT JOIN ASSENTOS A ON A.ID_Assento = EA.PK_Assento
